const promise=new Promise((resolve,reject)=>{setTimeout(()=>{let error=!1;resolve({name:"John",age:30})},1e3)});promise.then(user=>(console.log(user),user.name)).then(name=>(console.log(name),name.length)).then(nameLength=>{console.log(nameLength)}).catch(error=>(console.log(error),123)).then(x=>console.log("This will run no matter what",x));